me: Sync ruleset.skk.moe rules

on:
  schedule:
    # 每天 UTC 20:00 运行
    # 北京时间是第二天 04:00
    - cron: "0 20 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download rules
        run: |
          chmod +x scripts/update-rules.sh
          OUT_DIR=. ./scripts/update-rules.sh

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add Clash

          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          git commit -m "chore: sync rules"
          git push

