name: Sync ruleset.skk.moe rules

on:
  schedule:
    - cron: "0 20 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download rules
        run: |
          chmod +x scripts/update-rules.sh
          OUT_DIR=. ./scripts/update-rules.sh

      - name: Sort custom rules
        run: |
          chmod +x scripts/sort-custom.sh
          ./scripts/sort-custom.sh custom

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add Clash custom

          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          git commit -m "chore: sync rules"
          git push
